### ISSUE TITLE
Using Ningle with this Docker image

### ISSUE THREAD

**Issue by Pierre-Gilles** [Rudolph-Miller/dockerfile-clack#1]
Hi,

First of all thank you very much for this image, it's working like a charm :)

I would like to use [Ningle](https://github.com/fukamachi/ningle) in this image, but I can't get it work.

I've tried to create a Dockerfile like this : 

``` Dockerfile
FROM rudolphm/clack:latest

ADD app.lisp /usr/local/src/clack-test/

RUN ros -e "(ql:quickload :ningle)" 

CMD clackup --port 80 --server woo /usr/local/src/clack-test/app.lisp
EXPOSE 80
```

Then when I put in the app.lisp file the sample code in Ningle git repository : 

``` lisp
(defvar *app* (make-instance 'ningle:<app>))

(setf (ningle:route *app* "/")
      "Welcome to ningle!")

(setf (ningle:route *app* "/login" :method :POST)
      #'(lambda (params)
          (if (authorize (cdr (assoc "username" params :test #'string=))
                         (cdr (assoc "password" params :test #'string=)))
              "Authorized!"
              "Failed...Try again.")))

(clack:clackup *app*)
```

It seems that it's not working, I got a `Unhandled SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread #<SB-THREAD:THREAD
                                                         "main thread" RUNNING
                                                          {1002C00103}>:
  Package NINGLE does not exist.`

I'm not a lisp specialist, do you have any idea ?

Thank you very much for your answer,

**Comment by rudolph-miller** [comment]
Hi, nice to see you.

At first, please change your `app.lisp` file to

``` lisp
(ql:quickload :ningle)
(defvar *app* (make-instance 'ningle:<app>))

(setf (ningle:route *app* "/")
      "Welcome to ningle!")

(setf (ningle:route *app* "/login" :method :POST)
      #'(lambda (params)
          (if (authorize (cdr (assoc "username" params :test #'string=))
                         (cdr (assoc "password" params :test #'string=)))
              "Authorized!"
              "Failed...Try again.")))

*app*
```

And remove 

``` sh
RUN ros -e "(ql:quickload :ningle)"
```

line from your `Dockerfile`.
1. `(ql:quickload :ningle)` is not like `npm install` or `gem install` or so.
   - It does not install the specified package into some PATH directory.
   - It does load the specified package into your running Lisp image.
2. `clackup` command does `(clack:clackup ...)`, and you should remove `(clack:clackup ...)`.
   - So you can use `(clack:clackup ...)` without clackup command, like `ros app.lisp`.

Please retry with above.
If you have any other problem, please ask me. :)

**Comment by Pierre-Gilles** [comment]
Thank you very much for your quick answer, it works perfectly now :)

And thanks for explaining how it works in lisp ! Coming from a Node.js world, it's not easy to understand at the beginning how it really work. I wrote the dockerfile naively like for a Node.js server and thought (ql:quickload :ningle) would install ningle like npm install would. Now I understand !

**Comment by rudolph-miller** [comment]
You're welcome!

Most people from these area think so, and are confused.

:)
